# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-pygments}
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonathan Boyett"]
  s.date = %q{2011-01-20}
  s.description = %q{Sinatra extension for Pygments syntax highlighting}
  s.email = %q{jonathan@failingservers.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.homepage = %q{http://github.com/saysjonathan/sinatra-pygments}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Pygments for Sinatra}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.2"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5.0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0.9.2"])
      s.add_dependency(%q<rack-test>, [">= 0.5.0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0.9.2"])
    s.add_dependency(%q<rack-test>, [">= 0.5.0"])
  end
end

